// Code generated by goyacc - DO NOT EDIT.

package filter

import __yyfmt__ "fmt"

import (
	"fmt"
)

// End Of Filter
const EOF = 0

func unexpectedTokenErr(s string) error {
	return fmt.Errorf("unexpected token '%s'", s)
}

func couldNotParseErr(err error) error {
	return fmt.Errorf("could not parse expression: %w", err)
}

type yySymType struct {
	yys        int
	s          string
	labels     map[string]string
	expression Expression
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault = 57353
	yyEofCode = 57344
	AND       = 57347
	LABEL     = 57352
	NAMESPACE = 57351
	NOT       = 57346
	OR        = 57348
	PATTERN   = 57350
	RESOURCE  = 57349
	yyErrCode = 57345

	yyMaxDepth = 200
	yyTabOfs   = -12
)

var (
	yyPrec = map[int]int{
		NOT: 0,
		AND: 1,
		OR:  2,
	}

	yyXLAT = map[int]int{
		57344: 0,  // $end (12x)
		57347: 1,  // AND (11x)
		57348: 2,  // OR (11x)
		41:    3,  // ')' (10x)
		57350: 4,  // PATTERN (6x)
		40:    5,  // '(' (5x)
		57354: 6,  // expr (5x)
		57352: 7,  // LABEL (5x)
		57351: 8,  // NAMESPACE (5x)
		57346: 9,  // NOT (5x)
		57349: 10, // RESOURCE (5x)
		57355: 11, // labels (1x)
		57356: 12, // start (1x)
		57353: 13, // $default (0x)
		57345: 14, // error (0x)
	}

	yySymNames = []string{
		"$end",
		"AND",
		"OR",
		"')'",
		"PATTERN",
		"'('",
		"expr",
		"LABEL",
		"NAMESPACE",
		"NOT",
		"RESOURCE",
		"labels",
		"start",
		"$default",
		"error",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {12, 0},
		2:  {12, 1},
		3:  {6, 2},
		4:  {6, 2},
		5:  {6, 2},
		6:  {6, 3},
		7:  {6, 3},
		8:  {6, 3},
		9:  {6, 2},
		10: {11, 1},
		11: {11, 2},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [20][]uint8{
		// 0
		{11, 5: 18, 14, 17, 16, 19, 15, 12: 13},
		{12},
		{10, 21, 22},
		{4: 31},
		{4: 30},
		// 5
		{4: 28, 11: 27},
		{5: 18, 25, 17, 16, 19, 15},
		{5: 18, 20, 17, 16, 19, 15},
		{3, 21, 22, 3},
		{5: 18, 24, 17, 16, 19, 15},
		// 10
		{5: 18, 23, 17, 16, 19, 15},
		{4, 4, 22, 4},
		{5, 21, 22, 5},
		{1: 21, 22, 26},
		{6, 6, 6, 6},
		// 15
		{7, 7, 7, 7, 29},
		{2, 2, 2, 2, 2},
		{1, 1, 1, 1, 1},
		{8, 8, 8, 8},
		{9, 9, 9, 9},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 14

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			yylex.(*Lexer).result = truthyExpression{}
		}
	case 2:
		{
			yylex.(*Lexer).result = yyS[yypt-0].expression
		}
	case 3:
		{
			namespacePattern, namePattern := splitPattern(yyS[yypt-0].s)
			if err := validateNamespace(namespacePattern); err != nil {
				yylex.Error(couldNotParseErr(err).Error())
			}

			if err := validateResourceName(yyS[yypt-1].s, namePattern); err != nil {
				yylex.Error(couldNotParseErr(err).Error())
			}

			switch yyS[yypt-1].s {
			case "pod":
				yyVAL.expression = podExpression{namePattern: namePattern, namespacePattern: namespacePattern}
			case "job":
				yyVAL.expression = jobExpression{namePattern: namePattern, namespacePattern: namespacePattern}
			case "replicaset":
				yyVAL.expression = replicasetExpression{namePattern: namePattern, namespacePattern: namespacePattern}
			case "deployment":
				yyVAL.expression = deploymentExpression{namePattern: namePattern, namespacePattern: namespacePattern}
			case "service":
				yyVAL.expression = serviceExpression{namePattern: namePattern, namespacePattern: namespacePattern}
			}
		}
	case 4:
		{
			if err := validateNamespace(yyS[yypt-0].s); err != nil {
				yylex.Error(couldNotParseErr(err).Error())
			}

			yyVAL.expression = namespaceExpression{namespacePattern: yyS[yypt-0].s}
		}
	case 5:
		{
			yyVAL.expression = labelExpression{labelPatterns: yyS[yypt-0].labels}
		}
	case 6:
		{
			yyVAL.expression = yyS[yypt-1].expression
		}
	case 7:
		{
			yyVAL.expression = andExpression{left: yyS[yypt-2].expression, right: yyS[yypt-0].expression}
		}
	case 8:
		{
			yyVAL.expression = orExpression{left: yyS[yypt-2].expression, right: yyS[yypt-0].expression}
		}
	case 9:
		{
			yyVAL.expression = notExpression{inner: yyS[yypt-0].expression}
		}
	case 10:
		{
			key, val, err := splitLabelPattern(yyS[yypt-0].s)

			if err != nil {
				yylex.Error(fmt.Sprintf("could not parse label pattern '%s': %s", yyS[yypt-0].s, err))
			}

			yyVAL.labels = map[string]string{key: val}
		}
	case 11:
		{
			key, val, err := splitLabelPattern(yyS[yypt-0].s)

			if err != nil {
				yylex.Error(fmt.Sprintf("could not parse label pattern '%s': %s", yyS[yypt-1].labels, err))
			}

			yyVAL.labels[key] = val
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
