package deployer

type Deployer interface {
	// Up will create a k8s cluster and return any output and errors that occurred while provisioning, or if there is already a running cluster.
	Up() ([]byte, error)

	// IsUp will return true if this deployer has a running cluster, or false is not.
	IsUp() bool

	// Down will attempt to stop a running cluster and return any output and errors that occurred while deleting, or if there is no running cluster.
	Down() ([]byte, error)

	// Kubeconfig returns the path to the kubeconfig file used / generated by the cluster.
	Kubeconfig() string
}
